### ISSUE TITLE
Display name from SkySpark not available

### ISSUE THREAD

**Issue by NarcolepticEngineer** [NeedleInAJayStack/needleinajaystack-haystack-datasource#29]
Chart data only shows v0, v1, v2 etc. instead of display name or id. 

Currently, the only metadata that the api seems to be pulling in from SkySpark is the units and the type. And I can't determine how to change or adjust this to include dis or id to dynamically pick up which points or equipment are being passed in.

Screenshot of query expression and how it displays in the chart:
![image](https://github.com/NeedleInAJayStack/needleinajaystack-haystack-datasource/assets/28633309/2fbf79b5-0461-437c-8392-51234f708602)

Screenshot of Query Inspector:
![image](https://github.com/NeedleInAJayStack/needleinajaystack-haystack-datasource/assets/28633309/460d1d93-c048-4a3c-a3cf-25e327b4b398)

**Comment by NeedleInAJayStack** [comment]
Hey, thanks for reporting!

I actually wrote most of this package without access to SkySpark, so there are a few rough edges with it. I've got a fix for this issue now though: https://github.com/NeedleInAJayStack/needleinajaystack-haystack-datasource/pull/30

I'll push it through, tag a new version, and report back.

**Comment by NeedleInAJayStack** [comment]
Cool, I've released this feature as part of [v0.0.12](https://github.com/NeedleInAJayStack/needleinajaystack-haystack-datasource/releases/tag/v0.0.12). Grafana will review, and then you will be able to upgrade the data source plugin from within Grafana itself.

**Comment by NeedleInAJayStack** [comment]
v0.0.12 of the plugin has been released! https://grafana.com/grafana/plugins/needleinajaystack-haystack-datasource/

Feel free to re-open this issue if it doesn't resolve the display name problem. Thanks again for reporting!

**Comment by NarcolepticEngineer** [comment]
Thanks for the quick turnaround! Will let you know if this doesn't resolve!
